version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: redis:5.0.7
    container_name: redis
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  web:
    build:
      context: .
    container_name: web
    command: sh -c 'rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000'
    volumes:
      - .:/myapp
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    tty: true
    stdin_open: true

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local
